package com.model;


/**
 * TAdmin generated by MyEclipse Persistence Tools
 */

public class Car implements java.io.Serializable {


	private Integer id;
	private String no;
	private String stuname;
	private String jzname;
	private String tel;
	private String address;
	private String dw;
	private String bjnames;
	private String stupwd;
	private String jzpwd;
	private String url;
	private Integer yynum;
	private String bt;
	private String et;
	// Constructors

	/** default constructor */
	public Car() {
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNo() {
		return no;
	}

	public void setNo(String no) {
		this.no = no;
	}

	public String getStuname() {
		return stuname;
	}

	public void setStuname(String stuname) {
		this.stuname = stuname;
	}

	public String getJzname() {
		return jzname;
	}

	public void setJzname(String jzname) {
		this.jzname = jzname;
	}

	public String getTel() {
		return tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getDw() {
		return dw;
	}

	public void setDw(String dw) {
		this.dw = dw;
	}

	public String getStupwd() {
		return stupwd;
	}

	public void setStupwd(String stupwd) {
		this.stupwd = stupwd;
	}

	public String getJzpwd() {
		return jzpwd;
	}

	public void setJzpwd(String jzpwd) {
		this.jzpwd = jzpwd;
	}

	public String getBjnames() {
		return bjnames;
	}

	public void setBjnames(String bjnames) {
		this.bjnames = bjnames;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getBt() {
		return bt;
	}

	public void setBt(String bt) {
		this.bt = bt;
	}

	public String getEt() {
		return et;
	}

	public void setEt(String et) {
		this.et = et;
	}

	public Integer getYynum() {
		return yynum;
	}

	public void setYynum(Integer yynum) {
		this.yynum = yynum;
	}

}