package com.model;

import java.util.Date;

/**
 * TAdmin generated by MyEclipse Persistence Tools
 */

public class Demo implements java.io.Serializable {


	private Integer id;
	private String descs;
	private Date times;
	private String types;

	// Constructors

	/** default constructor */
	public Demo() {
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDescs() {
		return descs;
	}

	public void setDescs(String descs) {
		this.descs = descs;
	}

	public Date getTimes() {
		return times;
	}

	public void setTimes(Date times) {
		this.times = times;
	}

	public String getTypes() {
		return types;
	}

	public void setTypes(String types) {
		this.types = types;
	}
	
}