package com.model;

import java.util.Date;

/**
 * TAdmin generated by MyEclipse Persistence Tools
 */

public class Pp implements java.io.Serializable {

	// Fields

	private Integer id;
	private String names;
	private String types;
	private int nums;
	// Constructors

	/** default constructor */
	public Pp() {
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNames() {
		return names;
	}

	public void setNames(String names) {
		this.names = names;
	}

	public String getTypes() {
		return types;
	}

	public void setTypes(String types) {
		this.types = types;
	}

	public int getNums() {
		return nums;
	}

	public void setNums(int nums) {
		this.nums = nums;
	}

}