package com.model;

import java.util.Date;

/**
 * TAdmin generated by MyEclipse Persistence Tools
 */

public class Ts implements java.io.Serializable {

	// Fields

	private Integer id;
	private String names;//
	private Date times;
	private String descs;
	private String hfnames;//
	private String hfdescs;
	// Constructors

	/** default constructor */
	public Ts() {
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNames() {
		return names;
	}

	public void setNames(String names) {
		this.names = names;
	}

	public Date getTimes() {
		return times;
	}

	public void setTimes(Date times) {
		this.times = times;
	}

	public String getDescs() {
		return descs;
	}

	public void setDescs(String descs) {
		this.descs = descs;
	}

	public String getHfnames() {
		return hfnames;
	}

	public void setHfnames(String hfnames) {
		this.hfnames = hfnames;
	}

	public String getHfdescs() {
		return hfdescs;
	}

	public void setHfdescs(String hfdescs) {
		this.hfdescs = hfdescs;
	}

	

}