package com.model;

import java.util.Date;

/**
 * TAdmin generated by MyEclipse Persistence Tools
 */

public class Zp implements java.io.Serializable {

	// Fields

	private Integer id;
	private String titles;//
	private String descs;
	private String url;
	private String types;
	private String times;
	private String realname;
	// Constructors

	/** default constructor */
	public Zp() {
	}

	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTitles() {
		return titles;
	}

	public void setTitles(String titles) {
		this.titles = titles;
	}

	public String getDescs() {
		return descs;
	}

	public void setDescs(String descs) {
		this.descs = descs;
	}

	public String getTimes() {
		return times;
	}

	public void setTimes(String times) {
		this.times = times;
	}

	public String getUrl() {
		return url;
	}

	public void setUrl(String url) {
		this.url = url;
	}

	public String getRealname() {
		return realname;
	}

	public void setRealname(String realname) {
		this.realname = realname;
	}

	public String getTypes() {
		return types;
	}

	public void setTypes(String types) {
		this.types = types;
	}


}